Milestone 1: Responsive main page
prg-04/My-Portfolio pull request #1
Opened 2022-08-19 00:40 UTC by prg-04

In this Milestone, I have done the following step to set up a "My-Portfolio" repository:
 Create a new GitHub repo.

 Add a .gitignore file.

 Set up [a linter for HTML , CSS and Javascript](https://github.com/microverseinc/linters-config).

 Make sure that any files that are not relevant are ignored by git.

 Add a descriptive README file.

2022-08-19 02:22 UTC, ElsonOtake requested changes
STATUS: CHANGES REQUIRED 🟡 

Hi @prg-04,

Good job so far! 🎉 🎉 
Nice work by the way! 🏆 🏆 
There are some issues that you still need to work on to go to the next project but you are almost there! 🥲 🥲 

![woohoo-youre-almost](https://user-images.githubusercontent.com/77038610/154921145-1f7bb8f6-c843-4ba5-a534-6b840c600558.jpeg)

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️
- PR has a good title and summary. ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [OPTIONAL] On your next commits start the comment using capital letter. More details in [Document your repo in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/clean_repo.md).

Cheers and Happy coding!👏👏👏
Congratulations for your code until now!! 👏 👏 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 02:22 UTC, ElsonOtake commented on index.html
> +    <nav class="top-nav">
- [ ] Kindly use the `<header>` tag instead of `<nav>`. Because it is used as a page header, it usually contains the site's title or logo (or both) and the main site navigation.

2022-08-19 02:22 UTC, ElsonOtake commented on index.html
> +      </div>
- [ ] The menu items are located inside a `<nav>` tag for semantic reasons. Please follow this requirement for better readability.

2022-08-23 10:55 UTC, awais-amjed requested changes
# STATUS: CHANGES REQUIRED ♻️

Hi @prg-04 , 

Good job so far! 👏👏
There are some issues that you still need to work on to go to the next project but you are almost there! 😃🥳✨

## Highlights

- [x] Descriptive Pull Request ✔️
- [x] No Linter issues ✔️ 
- [x] Nice Design ✔️
- [x] Good code organization ✔️ 

![gif](https://media.giphy.com/media/qLWdMYX1NYF2g/giphy-downsized-large.gif)

## Required Changes ♻️

- [ ] Kindly note the differences between your design and Figma Design and try to fix them 😀
  - _Please use either your name or the image as a logo._
  - _Kindly reduce the size of the hamburger menu._
  - _Kindly fix the font size and margins to match the Figma Design._
  - _Align the social icons on the left side and include all the icons as shown in Figma Design._

_Your Design:_
![image](https://user-images.githubusercontent.com/73714615/186138348-8ebd7a9f-65c0-4b9f-887f-9f713d8b122a.png)

_Figma Design:_
![image](https://user-images.githubusercontent.com/73714615/186138954-592e7ee9-4591-40b5-a598-be6c757373fe.png)

_Also Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-23 10:55 UTC, awais-amjed commented on README.md
> +> This is a simple Hello-World Webpage that says "Hello Microverse"
Kindly add a description that is related to your Project 🤗

2022-08-23 10:55 UTC, awais-amjed commented on README.md
> +**After cloning the repository change the directory using 'cd Hello-World-Project' to access the files.**
Kindly try to use bullet points to give installation instructions as shown below

- Instruction 1
- Instruction 2  ...

2022-08-23 10:55 UTC, awais-amjed commented on index.html
> +      </div>
Kindly use either an image or your name for the logo so that it matches the Figma Design 😃

2022-08-23 10:55 UTC, awais-amjed commented on index.html
> +      <i class="fa-solid fa-bars"></i>
Please wrap the hamburger menu in a `<nav>` tag for semantic reasons 😃

2022-08-23 10:55 UTC, awais-amjed commented on index.html
> +        </div>
Kindly use a `<ul>` tag for the list of Social icons and `<li>` tag for each icon 😊

2022-08-23 14:01 UTC, thecodechaser approved these changes
## STATUS: APPROVED 🟢

## Hi @prg-04👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-23 14:04 UTC, merged