Milestone 2: Finished adding Popup
prg-04/My-Portfolio pull request #11
Opened 2022-09-16 05:23 UTC by prg-04

## In this Milestone, I have done the following step to create the Popup:

- [ ] Store the cards dynamically using javascript
- [ ] created both for both desktop and mobile version

2022-09-16 09:50 UTC, Munsa1 requested changes
Hi @prg-04 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
:heavy_check_mark: Descriptive Readme
:heavy_check_mark: Passing Linters
:heavy_check_mark: Correct Gitflow
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-16 09:50 UTC, Munsa1 commented on script.js
> +}
- [ ] Kindly make the pop-up responsive, meaning when you change the screen size from desktop to mobile , the pop=up must change from desktop to mobile as well.

2022-09-16 09:50 UTC, Munsa1 commented on script.js
> +function openPopup1(){
- [ ] The pop-up in mobile view is showing the destop version of the pop-up, kindly fix this issue.

Your version
![image](https://user-images.githubusercontent.com/81932478/190601577-ac5d593f-85fe-443b-80b9-21d3f97e5e7c.png)

Given design
![image](https://user-images.githubusercontent.com/81932478/190601720-c8120654-60e0-4a2a-aa2b-f554c154572b.png)

2022-09-16 09:50 UTC, Munsa1 commented on script.js
> +function closePopup1(){
- [ ] When I close the modal pop-up in desktop view, mobile pop-up shows, I think is happening because both the desktop modal pop-up and the mobile modal pop-up are be loaded together, kindly fix this issue.
- [ ] The modal popup should be loaded upon clicking the `see project` button and not on the `languages` kindly fix this

#### Modal should be linked to the button in the image below
![image](https://user-images.githubusercontent.com/81932478/190606067-3bf73d94-5379-43da-8845-fcf2c4d0ac6d.png)

2022-09-16 09:50 UTC, Munsa1 commented on script.js
> +let popup = document.querySelector('.popup');
- [ ] Kindly follow the given design, this includes the margins, padding,and images. Kindly fix your design.

#### Mobile

Your design
![image](https://user-images.githubusercontent.com/81932478/190609327-b622aa7b-329f-4e82-8b54-c393cce92bcd.png)

Figma design
![image](https://user-images.githubusercontent.com/81932478/190609693-3e1c2fdf-5a2e-442d-beaf-a1a0b82c96fb.png)

- Fix the broken image

#### Desktop

Your design
![image](https://user-images.githubusercontent.com/81932478/190610540-08477e0d-3922-457a-9388-445a366b1700.png)

Figma design
![image](https://user-images.githubusercontent.com/81932478/190610956-9243cb1f-4f52-4b69-99da-a4ab9582aa71.png)

- Kindly add some margin around your design
- Kindly position your close button nicely so that it looks like the Figma design

2022-09-17 04:16 UTC, MahmoudBakr23 approved these changes
Hi @prg-04  😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉 

**Highlights**
- Well done making the required changes from the previous reviewer

Cheers and Happy coding!👏👏👏

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-17 04:19 UTC, merged