Milestone: Finished Working UX Forms
prg-04/My-Portfolio pull request #3
Opened 2022-08-30 16:35 UTC by BlakeYall

In this Milestone, I have done the following step to set up a "My-Portfolio" repository.

- [ ] Updated the contact form.

2022-08-30 17:41 UTC, levy002 requested changes
## Hello @prg-04   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-30 17:41 UTC, levy002 commented on index.html
> +            <form action="/login" method="post" class="user-form">
- [ ] Kindly make sure when your form is submitted the data is collected by using the [Formspree service](https://formspree.io/html).

2022-08-30 17:41 UTC, levy002 commented on index.html
> +                  />
- [ ] Kindly make sure to add the `required` attribute which is a built-in HTML validation for preventing empty submission. :wink: 
- [ ] Kindly make sure to validate your name field to accept up to 30 chars. :wink:

2022-08-30 17:41 UTC, levy002 commented on index.html
> +                  />
- [ ] Kindly make sure to add the `required` attribute which is a built-in HTML validation for preventing empty submission. :wink:

2022-08-30 17:41 UTC, levy002 commented on index.html
> +                  ></textarea>
- [ ]  Kindly make sure to validate your message field to accept up to 500 chars. :wink:

2022-08-30 17:41 UTC, levy002 commented on styles.css
> +}
- [ ] Kindly make sure to align your contact section contacts correctly like on the provided Figma design. :wink: 

   - ### Your design
   ![image](https://user-images.githubusercontent.com/87197412/187505313-36a765b8-c086-4706-ac80-bd5090503aba.png)


  - ### Figma design
   ![image](https://user-images.githubusercontent.com/87197412/187505514-a05c918d-3ecc-4628-90b8-31b5542e4d30.png)

2022-08-30 17:41 UTC, levy002 commented on styles.css
> +}
- [ ] Kindly make sure to stick to the provided Figma while styling the `form`. :wink: 

   - ### Your design

   ![image](https://user-images.githubusercontent.com/87197412/187505880-ca084575-134e-4d10-a6db-72c57b0563b8.png)

  - ### Figma design
   ![image](https://user-images.githubusercontent.com/87197412/187505982-2ff46f9b-2f32-40ad-93ec-542ceeb60ee7.png)

2022-08-31 10:36 UTC, mahbubul14 requested changes
Hi @BlakeYall ,

Great work on making the changes requested by the previous reviewer 👏

You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

# Required Changes ♻️

- [ ] Kindly check the inline comments under the review. :arrow_down: 

###  To Highlights
:heavy_check_mark: No linter error.
:heavy_check_mark: Proper Github flow used.
:heavy_check_mark: Descriptive PR title & description.

### Optional suggestions

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-08-31 10:36 UTC, mahbubul14 commented on index.html
> +                <label>
- [ ] Kindly add placeholder text for the name and email address to match the Figma design. :+1:

2022-08-31 10:36 UTC, mahbubul14 commented on index.html
> +              </fieldset>
- [ ] Kindly remove the grey line from the border to match the Figma design. You can use "border: none" for it. :+1:

2022-08-31 10:36 UTC, mahbubul14 commented on index.html
> +              <a href="#"><i class="fa-solid fa-m"></i></a>
- [ ] Kindly decrease the size of your social icon to match the Figma design. :+1:

2022-08-31 11:39 UTC, prg-04 commented on index.html
> +              </fieldset>
The gray line is included in the figma design please check

2022-08-31 12:42 UTC, emmiiorji approved these changes
Hi @prg-04, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![congratulations](https://user-images.githubusercontent.com/20554583/187680746-3d378e1a-02d5-4cf6-9121-08709dcfd3c6.gif)


## Good Highlights ✅

- Good commit messages
- Implemented requested changes
- Adherence to GitHub flow


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-01 02:43 UTC, merged